// Code generated by Kitex v0.2.0. DO NOT EDIT.
package snow

import (
	"github.com/cloudwego/kitex/server"
	"test1/kitexTest/kitex_gen/snow"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler snow.Snow, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
